"use client";
import { useEffect, useState } from "react";
import { device, locationSequence, rooms, signalSequence, worker } from "@/data/mockRtlsData";
import { detectArea, geofences } from "@/lib/roomDetection";
import { ActivityEvent, ConnectionStatus, LocationPoint, MovementEvent } from "@/types/rtls";
import { getMovementStatus, getRelativeTime, getSignalQuality } from "@/lib/rtlsMetrics";

function RtlsMap({ position, activeRoom, trail, zoom, onZoom, onCenter, history }: { position: LocationPoint; activeRoom: string | null; trail: LocationPoint[]; zoom: number; onZoom: (delta: number) => void; onCenter: () => void; history: MovementEvent[] }) {
  const activeFill = (id: string) => activeRoom === id ? "#dce9ff" : "#f3f5f7";
  const [hoveredArea, setHoveredArea] = useState<string | null>(null);
  const viewWidth = 900 / zoom; const viewHeight = 500 / zoom; const viewX = Math.max(50, Math.min(950 - viewWidth, position.x - viewWidth / 2)); const viewY = Math.max(55, Math.min(555 - viewHeight, position.y - viewHeight / 2));
  const hovered = geofences.find((area) => area.id === hoveredArea);
  const hoveredHistory = hovered ? history.findLast((event) => event.roomId === hovered.id) : undefined;
  const popupLeft = hovered ? ((hovered.bounds.xMin + hovered.bounds.xMax) / 2 - viewX) / viewWidth * 100 : 0;
  const popupTop = hovered ? ((hovered.bounds.yMin + hovered.bounds.yMax) / 2 - viewY) / viewHeight * 100 : 0;
  return <div className="map-wrap"><div className="geofence-hover-layer" aria-label="Floor plan monitored areas">{geofences.map((area) => <button key={area.id} className="geofence-hover-target" aria-label={`View details for ${area.name}`} style={{ left: `${(area.bounds.xMin - viewX) / viewWidth * 100}%`, top: `${(area.bounds.yMin - viewY) / viewHeight * 100}%`, width: `${(area.bounds.xMax - area.bounds.xMin) / viewWidth * 100}%`, height: `${(area.bounds.yMax - area.bounds.yMin) / viewHeight * 100}%` }} onMouseEnter={() => setHoveredArea(area.id === activeRoom ? area.id : null)} onMouseLeave={() => setHoveredArea(null)} onFocus={() => setHoveredArea(area.id === activeRoom ? area.id : null)} onBlur={() => setHoveredArea(null)} />)}</div>{hovered && <div className="geofence-tooltip" role="status" style={{ left: `${popupLeft}%`, top: `${popupTop}%` }}><strong>{hovered.name}</strong><span className="tooltip-type">{hovered.type === "corridor" ? "Corridor" : "Monitored Area"}</span><div className="tooltip-row"><span>Status</span><b className={activeRoom === hovered.id ? "tooltip-active" : ""}>{activeRoom === hovered.id ? "ACTIVE" : "MONITORED"}</b></div><div className="tooltip-row"><span>Worker</span><b>{activeRoom === hovered.id ? worker.name : "—"}</b></div><div className="tooltip-row"><span>Device</span><b>{activeRoom === hovered.id ? worker.tagId : "—"}</b></div><div className="tooltip-row"><span>Signal</span><b>{activeRoom === hovered.id ? signalSequence[Math.max(0, locationSequence.findIndex((point) => point.x === position.x && point.y === position.y))] : "—"}</b></div><div className="tooltip-row"><span>Last update</span><b>{activeRoom === hovered.id ? position.timestamp : "—"}</b></div></div>}<svg className="floor-map" viewBox={`${viewX} ${viewY} ${viewWidth} ${viewHeight}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label="Building 01 indoor floor plan with RTLS tracking">
    <rect x="50" y="55" width="900" height="500" fill="#f8fafc" />
    <g aria-label="Architectural floor plan">
      <path d="M80 75H920V280 M920 330V515H80V75" fill="none" stroke="#425568" strokeWidth="10" strokeLinejoin="round" />
      <path d="M90 85H910V505H90Z" fill="#fbfcfd" />
      <rect x="90" y="85" width="350" height="195" fill={activeFill("R")} /><rect x="440" y="85" width="470" height="195" fill={activeFill("VER")} />
      <rect x="90" y="280" width="150" height="125" fill={activeFill("K")} /><rect x="90" y="405" width="150" height="100" fill={activeFill("T")} /><rect x="240" y="280" width="670" height="225" fill={activeFill("C")} />
      <path d="M440 85V155 M440 205V280 M90 280H500 M550 280H910 M240 280V330 M240 380V430 M240 480V505 M90 405H240" fill="none" stroke="#718395" strokeWidth="4" />
      <text className="map-label" x="265" y="165" textAnchor="middle">ROOM 1</text><text className="map-label" x="675" y="165" textAnchor="middle">ROOM 2</text><text className="map-label" x="165" y="330" textAnchor="middle">KITCHEN</text><text className="map-label" x="165" y="460" textAnchor="middle">TOILET</text><text className="map-label" x="575" y="390" textAnchor="middle">CORRIDOR</text>
    </g>
    <g aria-label="Dynamic RTLS layer">
      <polyline points={trail.map(({ x, y }) => `${x},${y}`).join(" ")} fill="none" stroke="#2d6cdf" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="7 8" opacity=".78" />
      <g transform={`translate(${position.x} ${position.y})`}><circle r="22" fill="#2d6cdf" fillOpacity=".16"><animate attributeName="r" values="18;29;18" dur="1.8s" repeatCount="indefinite" /><animate attributeName="opacity" values=".5;0;.5" dur="1.8s" repeatCount="indefinite" /></circle><circle r="12" fill="#2d6cdf" stroke="white" strokeWidth="4" /><circle r="4" fill="white" /><text x="20" y="-16" fill="#17345d" fontSize="14" fontWeight="700">Rahul</text></g>
    </g>
  </svg></div>;
}

export default function RtlsDashboard() {
  const [index, setIndex] = useState(0); const [running, setRunning] = useState(false); const [history, setHistory] = useState<MovementEvent[]>([]); const [zoom, setZoom] = useState(1);
  const position = locationSequence[index]; const detectedArea = detectArea(position.x, position.y, geofences); const activeRoom = detectedArea?.id ?? null; const currentRoom = rooms.find((room) => room.id === activeRoom); const trail = locationSequence.slice(0, index + 1); const signal = signalSequence[index]; const movementStatus = getMovementStatus(locationSequence[index - 1], position); const signalQuality = getSignalQuality(signal);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setIndex((value) => { if (value >= locationSequence.length - 1) { setRunning(false); return value; } return value + 1; }), 1150); return () => window.clearInterval(timer); }, [running]);
  useEffect(() => { if (!activeRoom) return; setHistory((items) => items.at(-1)?.roomId === activeRoom ? items : [...items, { roomId: activeRoom, roomName: currentRoom?.name ?? activeRoom, timestamp: position.timestamp }]); }, [activeRoom, currentRoom?.name, position.timestamp]);
  const statusText = running ? "LIVE TRACKING" : index === locationSequence.length - 1 ? "ROUTE COMPLETE" : "SIMULATION READY";
  return <div className="shell"><header className="topbar"><div><div className="eyebrow">Location intelligence</div><h1>RTLS Monitor</h1></div><div className="live-pill"><span className="live-dot" />{statusText}</div></header><div className="dashboard"><section className="card map-card"><div className="card-heading"><h2>Floor plan</h2><span className="map-meta">Live coordinate stream · {position.timestamp}</span></div><RtlsMap position={position} activeRoom={activeRoom} trail={trail} history={history} zoom={zoom} onZoom={(delta) => setZoom((value) => Math.max(1, Math.min(2.4, value + delta)))} onCenter={() => setZoom(1.8)} /></section><aside className="side"><section className="card info-card"><div className="section"><h3>Worker information</h3><div className="identity"><div className="avatar">RK</div><div><strong>{worker.name}</strong><span>{worker.employeeId}</span></div></div><div className="stats"><div className="stat"><label>Tag / Device ID</label><b>{device.tagId}</b></div><div className="stat"><label>Status</label><b className="online"><span className="status-dot" />{device.status}</b><small>{movementStatus}</small></div></div></div><div className="section"><h3>Current room</h3><div className="room-banner"><span>Detected area</span><strong>{currentRoom?.name ?? "Outside"}</strong></div></div><div className="section"><h3>Simulation</h3><div className="controls"><button className="primary" onClick={() => setRunning(true)} disabled={running || index === locationSequence.length - 1}>{index > 0 && !running ? "Resume movement" : "Start movement"}</button><button onClick={() => setRunning(false)} disabled={!running}>Pause</button><button onClick={() => { setRunning(false); setIndex(0); setHistory([]); }}>Reset</button></div></div><div className="section"><h3>Movement history</h3><div className="history">{history.map((event) => <div className="history-row" key={`${event.roomId}-${event.timestamp}`}><span className="history-marker" /><strong>{event.roomName}</strong><span className="history-time">{event.timestamp}</span></div>)}</div></div></section></aside></div></div>;
}
