"use client";
import { useEffect, useMemo, useState } from "react";
import { MovementEvent } from "@/types/rtls";

const API_BASE = process.env.NEXT_PUBLIC_RTLS_API_URL || "http://172.105.51.188:3005";
const GATEWAY_COORDINATES: Record<string, { x: number; y: number; roomKey: string }> = { "FCE8C07E0214": { x: 265, y: 165, roomKey: "R" }, "FCE8C07D10D4": { x: 675, y: 390, roomKey: "C" } };
type Employee = { employeeId: string; employeeName: string; department: string | null; bleMac: string };
type Location = Employee & { gatewayMac: string; gatewayName: string; currentZone: string; rssi: number; sampleCount: number; lastSeenAt: string; secondsAgo: number };

function RtlsMap({ locations, selectedId, onSelect }: { locations: Location[]; selectedId: string | null; onSelect: (id: string) => void }) {
  const selected = locations.find((item) => item.employeeId === selectedId); const activeRoom = selected ? GATEWAY_COORDINATES[selected.gatewayMac]?.roomKey : null; const fill = (id: string) => activeRoom === id ? "#dce9ff" : "#f3f5f7";
  return <div className="map-wrap"><svg className="floor-map" viewBox="50 55 900 500" role="img" aria-label="Live indoor RTLS floor plan"><rect x="50" y="55" width="900" height="500" fill="#f8fafc" /><path d="M80 75H920V280 M920 330V515H80V75" fill="none" stroke="#425568" strokeWidth="10" strokeLinejoin="round" /><path d="M90 85H910V505H90Z" fill="#fbfcfd" /><rect x="90" y="85" width="350" height="195" fill={fill("R")} /><rect x="440" y="85" width="470" height="195" fill={fill("VER")} /><rect x="90" y="280" width="150" height="125" fill={fill("K")} /><rect x="90" y="405" width="150" height="100" fill={fill("T")} /><rect x="240" y="280" width="670" height="225" fill={fill("C")} /><path d="M440 85V155 M440 205V280 M90 280H500 M550 280H910 M240 280V330 M240 380V430 M240 480V505 M90 405H240" fill="none" stroke="#718395" strokeWidth="4" /><text className="map-label" x="265" y="165" textAnchor="middle">ZONE NORTH</text><text className="map-label" x="575" y="390" textAnchor="middle">ZONE SOUTH</text>{locations.map((loc, index) => { const base = GATEWAY_COORDINATES[loc.gatewayMac] ?? { x: 500, y: 280 }; const x = base.x + (index % 3) * 35 - 35; const y = base.y + Math.floor(index / 3) * 35; const active = loc.employeeId === selectedId; return <g key={loc.employeeId} transform={`translate(${x} ${y})`} onClick={() => onSelect(loc.employeeId)} style={{ cursor: "pointer" }}><circle r={active ? 25 : 20} fill={active ? "#2563eb" : "#0284c7"} fillOpacity=".18" /><circle r={active ? 13 : 11} fill={active ? "#2563eb" : "#0284c7"} stroke="white" strokeWidth="3" /><circle r="4" fill="white" /><text x="18" y="-14" fill="#0f172a" fontSize={active ? "14" : "12"} fontWeight={active ? "800" : "600"}>{loc.employeeName}</text><title>{loc.employeeName} · {loc.currentZone} · {loc.rssi} dBm</title></g>; })}</svg></div>;
}

export default function RtlsDashboard() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [history, setHistory] = useState<MovementEvent[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let alive = true; const load = async () => { try { const res = await fetch(`${API_BASE}/api/employees`); const json = await res.json(); if (alive && json.status === "success") { setEmployees(json.data); setSelectedId((id) => id ?? json.data[0]?.employeeId ?? null); setError(null); } } catch { if (alive) setError("Unable to connect to the RTLS backend"); } }; load(); return () => { alive = false; }; }, []);
  useEffect(() => { let alive = true; const load = async () => { try { const res = await fetch(`${API_BASE}/api/locations?window=60&_=${Date.now()}`, { cache: "no-store" }); const json = await res.json(); if (alive && json.status === "success") { setLocations(json.data); setError(null); } } catch { if (alive) setError("Live location feed unavailable"); } }; load(); const timer = window.setInterval(load, 2500); return () => { alive = false; window.clearInterval(timer); }; }, []);
  const selectedEmployee = employees.find((item) => item.employeeId === selectedId); const selectedLocation = locations.find((item) => item.employeeId === selectedId); const onlineIds = useMemo(() => new Set(locations.map((item) => item.employeeId)), [locations]);
  useEffect(() => { if (!selectedLocation) return; setHistory((items) => items.at(-1)?.roomName === selectedLocation.currentZone ? items : [...items, { roomId: selectedLocation.gatewayMac, roomName: selectedLocation.currentZone, timestamp: new Date().toLocaleTimeString() }]); }, [selectedLocation?.currentZone, selectedLocation?.gatewayMac, selectedLocation?.lastSeenAt]);
  return <div className="shell"><header className="topbar"><div><div className="eyebrow">Location intelligence</div><h1>RTLS Monitor</h1></div><div className="live-pill"><span className="live-dot" />LIVE TRACKING · {locations.length} ON FLOOR</div></header>{error && <div className="api-error">{error}</div>}<div className="dashboard"><section className="card map-card"><div className="card-heading"><h2>Floor plan</h2><span className="map-meta">{selectedEmployee ? `Tracking: ${selectedEmployee.employeeName}` : "Waiting for employees"} · Refreshing every 2.5s</span></div><RtlsMap locations={locations} selectedId={selectedId} onSelect={setSelectedId} /></section><aside className="side"><section className="card info-card"><div className="section"><h3>All employees ({employees.length})</h3><div className="worker-list">{employees.map((employee) => <button className={`worker-option ${employee.employeeId === selectedId ? "selected" : ""}`} key={employee.employeeId} onClick={() => setSelectedId(employee.employeeId)}><span className="avatar">{employee.employeeName.slice(0, 2).toUpperCase()}</span><span><strong>{employee.employeeName}</strong><small>{employee.employeeId} · {employee.department || "Staff"}</small></span><em className={onlineIds.has(employee.employeeId) ? "live-status" : "offline-status"}>{onlineIds.has(employee.employeeId) ? "LIVE" : "OFFLINE"}</em></button>)}</div></div>{selectedEmployee && <div className="section"><h3>Worker details</h3><div className="identity"><div className="avatar">{selectedEmployee.employeeName.slice(0, 2).toUpperCase()}</div><div><strong>{selectedEmployee.employeeName}</strong><span>{selectedEmployee.employeeId} · {selectedEmployee.department || "Staff"}</span></div></div><div className="stats"><div className="stat"><label>BLE Beacon MAC</label><b>{selectedEmployee.bleMac}</b></div><div className="stat"><label>Signal</label><b>{selectedLocation ? `${selectedLocation.rssi} dBm` : "No signal"}</b><small>{selectedLocation ? `${selectedLocation.secondsAgo}s ago` : "Offline"}</small></div></div></div>}<div className="section"><h3>Current zone</h3><div className="room-banner"><span>Nearest gateway</span><strong>{selectedLocation?.currentZone || "Not detected"}</strong></div>{selectedLocation && <small className="gateway-line">via {selectedLocation.gatewayName}</small>}</div><div className="section"><h3>Recent history</h3><div className="history">{history.slice(-5).reverse().map((event, index) => <div className="history-row" key={`${event.timestamp}-${index}`}><span className="history-marker" /><strong>{event.roomName}</strong><span className="history-time">{event.timestamp}</span></div>)}</div></div></section></aside></div></div>;
}
